### ISSUE TITLE
按照文档无法运行

### ISSUE THREAD

**Issue by banana-a** [YMAndroid/Autolabor_Delta_1A_SLAM#1]
会卡在 source devel/setup.bash  好像没有这个文件

**Comment by YMAndroid** [comment]
代码clone下来之后，需要先编译，编译成功后会生成 devel 以及 build 文件夹； 
然后就可以 执行  source devel/setup.bash 指令了。










在 2020-09-29 19:28:54，"banana" <notifications@github.com> 写道：

会卡在 source devel/setup.bash 好像没有这个文件
